# Generated by Django 4.0.4 on 2022-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
